const data = [
  {
    id: 1,
    image: "https://ap-snek.com/wp-content/uploads/2021/08/5-zpov.png",
    name: "Біланасіннясоняшника230",
    grams: 230,
    price: 123,
    pricePack: 750,
    inPack: 25,
    isActive: false,
  },
  {
    id: 2,
    image: "https://ap-snek.com/wp-content/uploads/2021/08/1-zpov.png",
    name: "Преміумнасіннясоняшника80",
    grams: 230,
    price: 80,
    pricePack: 700,
    inPack: 25,
    isActive: false,
  },
  {
    id: 3,
    image: "https://ap-snek.com/wp-content/uploads/2021/08/2-zpov.png",
    name: "Синянасіннясоняшника120",
    grams: 230,
    price: 756,
    pricePack: 600,
    inPack: 25,
    isActive: false,
  },
  {
    id: 4,
    image: "https://ap-snek.com/wp-content/uploads/2021/08/15-zpov.png",
    name: "Ядро50насіннясоняшника ",
    grams: 230,
    price: 78,
    pricePack: 590,
    inPack: 25,
    isActive: false,
  },
  {
    id: 5,
    image: "https://ap-snek.com/wp-content/uploads/2021/08/14-zpov.png",
    name: "Гарбуз60",
    grams: 230,
    price: 50,
    pricePack: 580,
    inPack: 34,
    isActive: false,
  },
  {
    id: 6,
    image: "https://ap-snek.com/wp-content/uploads/2021/08/10-zpov.png",
    name: "Мікс80насіння соняшника",
    grams: 230,
    price: 87,
    pricePack: 500,
    inPack: 25,
    isActive: false,
  },
  {
    id: 7,
    image: "https://ap-snek.com/wp-content/uploads/2021/08/11-zpov.png",
    name: "Мікс120насіння соняшника",
    grams: 230,
    price: 98,
    pricePack: 150,
    inPack: 25,
    isActive: false,
  },
  {
    id: 8,
    image: "https://i.imgur.com/tjExWcK.png",
    name: "СухарикиGrizGoКраб35",
    grams: 230,
    price: 34,
    pricePack: 490,
    inPack: 25,
    isActive: false,
  },
  {
    id: 9,
    image: "https://i.imgur.com/OInSuaA.png",
    name: "СухарикиGrizGoСметанаізелень35",
    grams: 230,
    price: 56,
    pricePack: 580,
    inPack: 25,
    isActive: false,
  },
];

export default data;
